# check redirects from mintlify migration

import requests

def check_redirects(urls):
    results = []
    for url in urls:
        try:
            response = requests.get(url, allow_redirects=True, timeout=5)
            results.append((url, response.url, response.status_code))
        except requests.exceptions.RequestException as e:
            results.append((url, None, str(e)))
    return results

# list of URLs
urls = [
    "https://sensible.mintlify.app/docs/getting-started-ai",
    "https://sensible.mintlify.app/docs/author",
    "https://sensible.mintlify.app/docs/sections-example-zip",
    "https://sensible.mintlify.app/docs/sections-example-table-grid",
    "https://sensible.mintlify.app/docs/sections-example-nested-table",
    "https://sensible.mintlify.app/docs/sections-example-nested-columns",
    "https://sensible.mintlify.app/docs/sections-example-loss-run",
    "https://sensible.mintlify.app/docs/sections-example-labeled-rows",
    "https://sensible.mintlify.app/docs/sections-example-external-range",
    "https://sensible.mintlify.app/docs/sections-example-copy-to-section",
    "https://sensible.mintlify.app/docs/sections-example-copy-from-sections",
    "https://sensible.mintlify.app/docs/split-lines",
    "https://sensible.mintlify.app/docs/scale",
    "https://sensible.mintlify.app/docs/rotate-page",
    "https://sensible.mintlify.app/docs/remove-header",
    "https://sensible.mintlify.app/docs/remove-footer",
    "https://sensible.mintlify.app/docs/page-range",
    "https://sensible.mintlify.app/docs/ocr-preprocessor",
    "https://sensible.mintlify.app/docs/nlp",
    "https://sensible.mintlify.app/docs/merge-lines",
    "https://sensible.mintlify.app/docs/ligature",
    "https://sensible.mintlify.app/docs/deskew",
    "https://sensible.mintlify.app/docs/text-table",
    "https://sensible.mintlify.app/docs/signature",
    "https://sensible.mintlify.app/docs/row",
    "https://sensible.mintlify.app/docs/region",
    "https://sensible.mintlify.app/docs/regex",
    "https://sensible.mintlify.app/docs/passthrough",
    "https://sensible.mintlify.app/docs/paragraph",
    "https://sensible.mintlify.app/docs/nearest-checkbox",
    "https://sensible.mintlify.app/docs/label",
    "https://sensible.mintlify.app/docs/intersection",
    "https://sensible.mintlify.app/docs/fixed-table",
    "https://sensible.mintlify.app/docs/document-range",
    "https://sensible.mintlify.app/docs/column",
    "https://sensible.mintlify.app/docs/checkbox",
    "https://sensible.mintlify.app/docs/box",
    "https://sensible.mintlify.app/docs/summarizer",
    "https://sensible.mintlify.app/docs/query-group",
    "https://sensible.mintlify.app/docs/nlp-table",
    "https://sensible.mintlify.app/docs/list",
    "https://sensible.mintlify.app/docs/types",
    "https://sensible.mintlify.app/docs/method",
    "https://sensible.mintlify.app/docs/match",
    "https://sensible.mintlify.app/docs/anchor",
    "https://sensible.mintlify.app/docs/ocr-level",
    "https://sensible.mintlify.app/docs/ocr-engine",
    "https://sensible.mintlify.app/docs/fingerprint-mode",
    "https://sensible.mintlify.app/docs/verbosity",
    "https://sensible.mintlify.app/docs/fingerprint",
    "https://sensible.mintlify.app/docs/table-methods",
    "https://sensible.mintlify.app/docs/senseml",
    "https://sensible.mintlify.app/docs/section-nuances",
    "https://sensible.mintlify.app/docs/ocr",
    "https://sensible.mintlify.app/docs/match-arrays",
    "https://sensible.mintlify.app/docs/lines",
    "https://sensible.mintlify.app/docs/ligatures",
    "https://sensible.mintlify.app/docs/file-types",
    "https://sensible.mintlify.app/docs/field-order",
    "https://sensible.mintlify.app/docs/coverage",
    "https://sensible.mintlify.app/docs/bag-of-words",
    "https://sensible.mintlify.app/docs/anchor-nuances",
    "https://sensible.mintlify.app/docs/accuracy-measures",
    "https://sensible.mintlify.app/docs/zip",
    "https://sensible.mintlify.app/docs/suppress-output",
    "https://sensible.mintlify.app/docs/split",
    "https://sensible.mintlify.app/docs/pick-values",
    "https://sensible.mintlify.app/docs/mapper",
    "https://sensible.mintlify.app/docs/constant",
    "https://sensible.mintlify.app/docs/concatenate",
    "https://sensible.mintlify.app/docs/get-file-metadata",
    "https://sensible.mintlify.app/docs/custom-computation",
    "https://sensible.mintlify.app/docs/copy-to-section",
    "https://sensible.mintlify.app/docs/copy-from-sections",
    "https://sensible.mintlify.app/docs/add-computed-fields",
    "https://sensible.mintlify.app/docs/senseml-reference-introduction",
    "https://sensible.mintlify.app/docs/table-tips",
    "https://sensible.mintlify.app/docs/query-group-tips",
    "https://sensible.mintlify.app/docs/list-tips",
    "https://sensible.mintlify.app/docs/prompt",
    "https://sensible.mintlify.app/docs/ui",
    "https://sensible.mintlify.app/docs/color",
    "https://sensible.mintlify.app/docs/repeat-layouts",
    "https://sensible.mintlify.app/docs/portfolio",
    "https://sensible.mintlify.app/docs/library-quickstart",
    "https://sensible.mintlify.app/docs/getting-started",
    "https://sensible.mintlify.app/docs/zapier-tutorial-2",
    "https://sensible.mintlify.app/docs/zapier-getting-started",
    "https://sensible.mintlify.app/docs/excel-reference",
    "https://sensible.mintlify.app/docs/sdk-guides",
    "https://sensible.mintlify.app/docs/quickstart",
    "https://sensible.mintlify.app/docs/classify",
    "https://sensible.mintlify.app/docs/troubleshoot",
    "https://sensible.mintlify.app/docs/test-before-integrating-configs",
    "https://sensible.mintlify.app/docs/performance",
    "https://sensible.mintlify.app/docs/handwriting",
    "https://sensible.mintlify.app/docs/go-live",
    "https://sensible.mintlify.app/docs/fallbacks",
    "https://sensible.mintlify.app/docs/validate-extractions",
    "https://sensible.mintlify.app/docs/troubleshoot-llms",
    "https://sensible.mintlify.app/docs/metrics",
    "https://sensible.mintlify.app/docs/confidence",
    "https://sensible.mintlify.app/docs/api-tutorial-webhook",
    "https://sensible.mintlify.app/docs/api-tutorial-sync",
    "https://sensible.mintlify.app/docs/api-tutorial-async-2",
    "https://sensible.mintlify.app/docs/api-tutorial-async-1",
    "https://sensible.mintlify.app/docs/examples",
    "https://sensible.mintlify.app/docs/api-reference",
    "https://sensible.mintlify.app/reference/classify-document-by-type-sync",
    "https://sensible.mintlify.app/reference/introduction",
    "https://sensible.mintlify.app/reference/extract-data-from-a-document",
    "https://sensible.mintlify.app/reference/authentication",
    "https://sensible.mintlify.app/reference/retrieve-extraction-by-id",
    "https://sensible.mintlify.app/reference/list-extractions",
    "https://sensible.mintlify.app/reference/get-extraction-statistics",
    "https://sensible.mintlify.app/reference/extract-portfolio-at-your-url",
    "https://sensible.mintlify.app/reference/extract-portfolio-at-a-sensible-url",
    "https://sensible.mintlify.app/reference/get-excel-extraction",
    "https://sensible.mintlify.app/reference/get-csv-extraction",
    "https://sensible.mintlify.app/reference/extract-doc-at-your-url",
    "https://sensible.mintlify.app/reference/extract-doc-at-your-url-using-config",
    "https://sensible.mintlify.app/reference/extract-doc-at-a-sensible-url",
    "https://sensible.mintlify.app/reference/extract-doc-at-a-sensible-url-using-specified-config",
    "https://sensible.mintlify.app/reference/extract-data-from-a-document-using-specified-config",
    "https://sensible.mintlify.app/reference/update-metadata-for-a-reference-document",
    "https://sensible.mintlify.app/reference/unassociate-reference-document-from-configuration",
    "https://sensible.mintlify.app/reference/list-all-reference-documents-in-a-document-type",
    "https://sensible.mintlify.app/reference/get-reference-document-metadata",
    "https://sensible.mintlify.app/reference/extract-all-text-from-reference-document",
    "https://sensible.mintlify.app/reference/delete-reference-document",
    "https://sensible.mintlify.app/reference/create-reference-document",
    "https://sensible.mintlify.app/reference/update-document-type",
    "https://sensible.mintlify.app/reference/list-document-types-for-this-account",
    "https://sensible.mintlify.app/reference/get-document-type-metadata",
    "https://sensible.mintlify.app/reference/delete-document-type",
    "https://sensible.mintlify.app/reference/create-document-type",
    "https://sensible.mintlify.app/reference/update-configuration",
    "https://sensible.mintlify.app/reference/publish-configuration-to-an-environment",
    "https://sensible.mintlify.app/reference/list-versions-for-a-configuration",
    "https://sensible.mintlify.app/reference/list-configurations-in-a-document-type",
    "https://sensible.mintlify.app/reference/get-configuration",
    "https://sensible.mintlify.app/reference/get-configuration-by-version",
    "https://sensible.mintlify.app/reference/delete-draft-or-unpublish-configuration",
    "https://sensible.mintlify.app/reference/delete-configuration",
    "https://sensible.mintlify.app/reference/create-configuration-in-a-document-type",
    "https://sensible.mintlify.app/reference/classify-document-by-type"

]

# Check redirects for the list of URLs
results = check_redirects(urls)

# Write the results to a text file
with open("redirect_results.txt", "w+") as file:
    for result in results:
        file.write(f"{result}\n")

print("Results have been written to redirect_results.txt")
